### ISSUE TITLE
Helm install: name too long on microk8s

### ISSUE THREAD

**Issue by fdrobnic** [FIWARE/production-on-k8s#2]
When installing the business-api-ecosystem helm chart, the following error occurs in microk8s:

    Error: Deployment.apps "business-api-ecosystem-biz-ecosystem-charging-backend" is invalid: spec.template.spec.initContainers[0].name: Invalid value: "business-api-ecosystem-biz-ecosystem-charging-backend-wait-for-mongodb": must be no more than 63 characters

The install succeeds if shorter name is used, e.g. `bae`:

    helm install -f ./values/values-marketplace.yml --namespace marketplace bae fiware/business-api-ecosystem

It would be useful to mention it in README.md.

**Comment by fdrobnic** [comment]
Well, after above step was taken another problem arose. This is the status of the logic-proxy deployment (maybe too long name again?):

status:
  observedGeneration: 1
  unavailableReplicas: 1
  conditions:
    - type: Available
      status: 'False'
      lastUpdateTime: '2021-05-10T17:34:06Z'
      lastTransitionTime: '2021-05-10T17:34:06Z'
      reason: MinimumReplicasUnavailable
      message: Deployment does not have minimum availability.
    - type: ReplicaFailure
      status: 'True'
      lastUpdateTime: '2021-05-10T17:34:05Z'
      lastTransitionTime: '2021-05-10T17:34:05Z'
      reason: FailedCreate
      message: >-
        pods "bae-business-api-ecosystem-biz-ecosystem-logic-proxy-68694495cd-"
        is forbidden: error looking up service account marketplace/ssc:
        serviceaccount "ssc" not found
    - type: Progressing
      status: 'False'
      lastUpdateTime: '2021-05-10T17:44:06Z'
      lastTransitionTime: '2021-05-10T17:44:06Z'
      reason: ProgressDeadlineExceeded
      message: >-
        ReplicaSet
        "bae-business-api-ecosystem-biz-ecosystem-logic-proxy-68694495cd" has
        timed out progressing.

**Comment by dwendland** [comment]
About your first comment:
This is rather a problem with the Helm Chart. It deploys several init containers in order to check whether the depending containers are available. These have pretty long names. Need to think about how to limit it within the chart depending on the release name.
For the moment, changing the release name in the instructions and adding a note in the Readme is a good option. Thanks! I'll update this.

About your second comment:
It looks like there is a problem with the specified service account. Did you create it? If not, try setting
serviceAccount:
    create: true
this should create it during deployment.

**Comment by fdrobnic** [comment]
Yes, serviceAccount is in order now.

**Comment by dwendland** [comment]
If this is solved, then the issue can be closed.
